version: '3'
services:
  wallet-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: 'wallet-server'
    restart: always
    ports:
      - '6565:6565'
    volumes:
      - ./:/wallet
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pgsql:5432/wallet
      SPRING_DATASOURCE_USERNAME: wallet
      SPRING_DATASOURCE_PASSWORD: w@11Et!
    depends_on:
      - pgsql
    networks:
      walletnet:
        aliases:
          - walletserver
  pgsql:
    image: sameersbn/postgresql:10
    ports:
      - "5432:5432"
    restart: always
    environment:
      - DEBUG=false
      - DB_USER=wallet
      - DB_PASS=w@11Et!
      - DB_NAME=wallet
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      walletnet:
        aliases:
          - pgsql

volumes:
  db_data:

networks:
  walletnet:
    external: true