spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wallet
    username: postgres
    password: postgres
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
    database: postgresql

#logging:
#  level:
#    root:
#      OFF