spring:
  datasource:
    #    driver-class-name: org.postgresql.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:postgresql://localhost:5432/test
    username: postgres
    password: postgres
    initialization-mode: always # todo remove after Docker
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
    database: postgresql


log4j:
  logger:
    org:
      hibernate:
        persister:
          entity: DEBUG